name: Python CI Pipeline

on:
push:
branches:
- main
pull_request:
branches:
- main

jobs:
build-and-test:
runs-on: ubuntu-latest

# We will use Python 3.10, which is compatible with the pinned TensorFlow 2.11.0
strategy:
  matrix:
    python-version: ['3.10']

steps:
- name: Checkout Repository and LFS Files
  uses: actions/checkout@v4
  with:
    # CRUCIAL: Ensures the large model.keras file is downloaded correctly
    lfs: true

- name: Set up Python ${{ matrix.python-version }}
  uses: actions/setup-python@v5
  with:
    python-version: ${{ matrix.python-version }}

# Install the dependencies from requirements.txt (including the fixed TensorFlow/NumPy versions)
- name: Install Dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    
# Download NLTK data required by your scripts (since this was in your original Dockerfile)
- name: Download NLTK Data
  run: |
    python -m nltk.downloader stopwords punkt wordnet

# ----------------------------------------------------
# FINAL SMOKE TEST EXECUTION
# This runs the predict script to ensure the model loads and executes.
# ----------------------------------------------------
- name: Run Model Smoke Test
  # We use PYTHONPATH=. so Python can find modules in the 'src' directory
  run: |
    echo "Running prediction script to test model loading and execution..."
    PYTHONPATH=. python src/predict.py --model models/model.keras --text "This is a quick test of model loading."
