name: Python CI Pipeline
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository and LFS Files
      uses: actions/checkout@v4
      with:
        # Crucial for downloading the model.keras binary
        lfs: true

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      # We use working-directory to ensure requirements.txt is found
      working-directory: ${{ github.workspace }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Download NLTK data required by your scripts
        python -m nltk.downloader stopwords punkt wordnet

    - name: Run Model Smoke Test
      # We use working-directory to ensure src/predict.py is found
      working-directory: ${{ github.workspace }}
      run: |
        echo "Running prediction script to test model loading and execution..."
        # PYTHONPATH=. ensures local modules (like src) are found
        PYTHONPATH=. python src/predict.py --model models/model.keras --text "This is a quick test of model loading."
